sudo: false

language: python

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Use Python 3.7 on xenial with sudo since it's not available on trusty yet
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a

# command to install dependencies
install:
  - pip install .[test]
  # Install through setup.py should be redundant because of the preceding pip
  # install. Just doing this to try to catch any high-level errors.
  - python setup.py install

before_script:
  - python -m dxlclient provisionconfig sample 127.0.0.1 client -u admin -p password
  - cat sample/dxlclient.config

# command to run tests
script:
  - python setup.py ci
